apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id>
  name: <infrastructure_id>-odf
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id>
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id>
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra
    spec:
      metadata:
        creationTimestamp: null
        labels:
        node-role.kubernetes.io/infra: ""
        node-role.kubernetes.io: infra
        cluster.ocs.openshift.io/openshift-storage: ""
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
      providerSpec:
        value:
          numCoresPerSocket: 2
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 8192
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: Openshift-Hmo
          metadata:
            creationTimestamp: null
          numCPUs: 4
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: <vcenter_datacenter_name>
            datastore: <vcenter_datastore_name>
            folder: <vcenter_vm_folder_path>
            resourcePool: <vsphere_resource_pool>
            server: <vcenter_server_ip>
          template: <infrastructure_id>-rhcos
          apiVersion: machine.openshift.io/v1beta1
